# Generated by Django 5.0.3 on 2024-03-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='number_room',
            field=models.IntegerField(verbose_name='Номер помещения'),
        ),
    ]
