# Generated by Django 5.0.3 on 2024-03-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_dayweek_entryexit_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='biometrics',
            field=models.CharField(max_length=100, verbose_name='Биометрические данные'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fio',
            field=models.CharField(max_length=70, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='passport_details',
            field=models.CharField(max_length=150, verbose_name='Паспортные данные'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
    ]
