# Generated by Django 5.0.3 on 2024-04-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_address_alter_customuser_biometrics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryexit',
            name='entry',
            field=models.BooleanField(blank=True, null=True, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='entryexit',
            name='main_entry',
            field=models.BooleanField(blank=True, null=True, verbose_name='Вход на предприятие'),
        ),
    ]
